---
apiVersion: v1
kind: Service
metadata:
  name: lore
spec:
  selector:
    app.kubernetes.io/name: lore
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
