package pdf

import (
	"bytes"
	"compress/zlib"
	"context"
	"encoding/base64"
	"io"
	"os"
)

// TestResult describes the generated PDF returned by a PDF service test.
type TestResult struct {
	File      *os.File
	PageCount int
	Size      int64
}

// RenderTest renders Lore's fixed PDF diagnostic document and returns it for inspection.
func RenderTest(ctx context.Context, endpoint string) (TestResult, func(), error) {
	file, cleanup, err := Render(ctx, endpoint, "Lore PDF service test", "en", testBody())
	if err != nil {
		return TestResult{}, cleanup, err
	}

	info, err := file.Stat()
	if err != nil {
		cleanup()
		return TestResult{}, func() {}, err
	}

	pageCount, err := pdfPageCount(file)
	if err != nil {
		pageCount = 0
	}

	return TestResult{
		File:      file,
		PageCount: pageCount,
		Size:      info.Size(),
	}, cleanup, nil
}

// testBody returns a two-page self-contained document that exercises common export features.
func testBody() string {
	image := base64.StdEncoding.EncodeToString([]byte(testImageSVG))

	return `
<section>
	<p style="margin:0 0 8px;color:#64748b;font-size:9pt;font-weight:700;letter-spacing:.08em;text-transform:uppercase">Rendering diagnostics</p>
	<h2 style="margin-top:0">Typography, color, tables, and images</h2>
	<p>This document is generated by Lore and rendered by the configured PDF service. It includes <strong>bold text</strong>, <em>italic text</em>, a <a href="https://example.invalid">link</a>, and inline code such as <code>$(VAR_NAME)</code>.</p>
	<p><strong>Unicode:</strong> ä ö ü ß é · → · ✓ · 日本語 · 中文 · 한국어</p>

	<div class="callout warning">
		<strong>Warning callout</strong><br>
		Backgrounds, borders, spacing, and inline <code>code</code> should remain easy to read.
	</div>

	<div style="display:flex;align-items:center;gap:18px;margin:18px 0">
		<img src="data:image/svg+xml;base64,` + image + `" alt="Lore PDF test illustration" style="width:150px;height:90px;border:1px solid #d4d4d8;border-radius:8px">
		<div>
			<strong>Embedded image</strong>
			<p style="margin:4px 0 0;color:#64748b">The image is embedded as a data URL, just like media in a self-contained Lore PDF export.</p>
		</div>
	</div>

	<table>
		<thead><tr><th>Feature</th><th>Expected result</th><th>Status</th></tr></thead>
		<tbody>
			<tr><td>Typography</td><td>Readable weights and Unicode</td><td style="background:#dcfce7">Check visually</td></tr>
			<tr><td>Image</td><td>Blue illustration above</td><td style="background:#dbeafe">Check visually</td></tr>
			<tr><td>Table</td><td>Visible borders and fills</td><td style="background:#fef3c7">Check visually</td></tr>
		</tbody>
	</table>
</section>

<section style="break-before:page">
	<p style="margin:0 0 8px;color:#64748b;font-size:9pt;font-weight:700;letter-spacing:.08em;text-transform:uppercase">Page 2</p>
	<h2 style="margin-top:0">Pagination and code rendering</h2>
	<p>This content is intentionally forced onto a second page so Lore can report the generated page count.</p>

	<pre><code>export PDF_SERVICE=http://html2pdf:8080/render
curl -X POST "$PDF_SERVICE" \\
  -H 'Content-Type: text/html; charset=utf-8' \\
  --data '&lt;h1&gt;Lore PDF test&lt;/h1&gt;'</code></pre>

	<blockquote>
		The PDF service test verifies transport and document structure. The administrator decides whether the visual result is acceptable.
	</blockquote>

	<table>
		<thead><tr><th>Check</th><th>What Lore verifies</th></tr></thead>
		<tbody>
			<tr><td>Endpoint</td><td>The configured service answered the render request.</td></tr>
			<tr><td>PDF</td><td>The response is a PDF with a valid PDF signature.</td></tr>
			<tr><td>Pages</td><td>The diagnostic document should contain exactly two pages.</td></tr>
			<tr><td>Size</td><td>The returned document size is reported for context.</td></tr>
		</tbody>
	</table>
</section>`
}

const testImageSVG = `<svg xmlns="http://www.w3.org/2000/svg" width="300" height="180" viewBox="0 0 300 180">
<rect width="300" height="180" rx="18" fill="#eff6ff"/>
<rect x="24" y="24" width="252" height="132" rx="14" fill="#ffffff" stroke="#93c5fd" stroke-width="4"/>
<circle cx="82" cy="90" r="34" fill="#2563eb"/>
<path d="M70 90l9 9 18-22" fill="none" stroke="#ffffff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
<rect x="136" y="62" width="102" height="12" rx="6" fill="#1e3a8a"/>
<rect x="136" y="86" width="82" height="10" rx="5" fill="#60a5fa"/>
<rect x="136" y="108" width="94" height="10" rx="5" fill="#bfdbfe"/>
</svg>`

// pdfPageCount counts page objects in plain or Flate-compressed PDF object streams.
func pdfPageCount(file *os.File) (int, error) {
	position, err := file.Seek(0, io.SeekCurrent)
	if err != nil {
		return 0, err
	}
	defer func() { _, _ = file.Seek(position, io.SeekStart) }()

	if _, err := file.Seek(0, io.SeekStart); err != nil {
		return 0, err
	}

	data, err := io.ReadAll(io.LimitReader(file, maxPDFBytes+1))
	if err != nil {
		return 0, err
	}

	count := countPDFPageObjects(withoutPDFStreamBodies(data))
	for _, decoded := range decodedFlateStreams(data) {
		count += countPDFPageObjects(decoded)
	}

	return count, nil
}

// withoutPDFStreamBodies removes raw stream payloads before scanning the PDF body.
// Compressed object streams may contain literal /Type /Page bytes by chance, and
// those objects are counted separately after the stream has been decoded.
func withoutPDFStreamBodies(data []byte) []byte {
	stripped := append([]byte(nil), data...)
	offset := 0

	for offset < len(data) {
		relative := bytes.Index(data[offset:], []byte("stream"))
		if relative < 0 {
			break
		}

		stream := offset + relative
		start := stream + len("stream")
		if start < len(data) && data[start] == '\r' {
			start++
		}
		if start >= len(data) || data[start] != '\n' {
			offset = start
			continue
		}
		start++

		relativeEnd := bytes.Index(data[start:], []byte("endstream"))
		if relativeEnd < 0 {
			break
		}

		end := start + relativeEnd
		for index := start; index < end; index++ {
			stripped[index] = ' '
		}

		offset = end + len("endstream")
	}

	return stripped
}

// countPDFPageObjects counts /Type /Page dictionaries while excluding /Pages nodes.
func countPDFPageObjects(data []byte) int {
	count := 0
	offset := 0

	for offset < len(data) {
		index := bytes.Index(data[offset:], []byte("/Type"))
		if index < 0 {
			break
		}

		cursor := offset + index + len("/Type")
		for cursor < len(data) && isPDFWhitespace(data[cursor]) {
			cursor++
		}
		if cursor >= len(data) || data[cursor] != '/' {
			offset = cursor
			continue
		}

		cursor++
		start := cursor
		for cursor < len(data) && !isPDFDelimiter(data[cursor]) {
			cursor++
		}
		if string(data[start:cursor]) == "Page" {
			count++
		}

		offset = cursor
	}

	return count
}

// decodedFlateStreams returns streams using the common FlateDecode PDF filter.
func decodedFlateStreams(data []byte) [][]byte {
	var decoded [][]byte
	offset := 0

	for offset < len(data) {
		relative := bytes.Index(data[offset:], []byte("stream"))
		if relative < 0 {
			break
		}

		stream := offset + relative
		start := stream + len("stream")
		if start < len(data) && data[start] == '\r' {
			start++
		}
		if start >= len(data) || data[start] != '\n' {
			offset = start
			continue
		}
		start++

		relativeEnd := bytes.Index(data[start:], []byte("endstream"))
		if relativeEnd < 0 {
			break
		}
		end := start + relativeEnd
		offset = end + len("endstream")

		preambleStart := max(0, stream-512)
		if !bytes.Contains(data[preambleStart:stream], []byte("/FlateDecode")) {
			continue
		}

		reader, err := zlib.NewReader(bytes.NewReader(bytes.TrimRight(data[start:end], "\r\n")))
		if err != nil {
			continue
		}

		content, err := io.ReadAll(reader)
		_ = reader.Close()
		if err == nil {
			decoded = append(decoded, content)
		}
	}

	return decoded
}

func isPDFWhitespace(value byte) bool {
	switch value {
	case 0, '\t', '\n', '\f', '\r', ' ':
		return true
	default:
		return false
	}
}

func isPDFDelimiter(value byte) bool {
	if isPDFWhitespace(value) {
		return true
	}

	switch value {
	case '(', ')', '<', '>', '[', ']', '{', '}', '/', '%':
		return true
	default:
		return false
	}
}
