// Command generate-icons creates Lore's Lucide icon picker catalog.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

var registration = regexp.MustCompile(`registerIcon\("([^"]+)"`)

// main generates the sorted icon catalog from the pinned Lucide module.
func main() {
	moduleDir, err := lucideModuleDir()
	if err != nil {
		fail(err)
	}
	source, err := os.ReadFile(filepath.Join(moduleDir, "icons.go"))
	if err != nil {
		fail(fmt.Errorf("read Lucide catalog: %w", err))
	}

	matches := registration.FindAllSubmatch(source, -1)
	if len(matches) == 0 {
		fail(fmt.Errorf("no registered icons in Lucide catalog"))
	}
	names := make([]string, 0, len(matches))
	seen := make(map[string]struct{}, len(matches))
	for _, match := range matches {
		name := string(match[1])
		if _, exists := seen[name]; exists {
			continue
		}
		seen[name] = struct{}{}
		names = append(names, name)
	}
	slices.Sort(names)

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("package icons\n\n")
	output.WriteString("var navigationOptions = []Option{\n")
	for _, name := range names {
		fmt.Fprintf(&output, "\t{Name: %q, Label: %q},\n", name, label(name))
	}
	output.WriteString("}\n\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fail(fmt.Errorf("format generated catalog: %w", err))
	}
	if err := os.WriteFile("catalog_gen.go", formatted, 0o644); err != nil {
		fail(fmt.Errorf("write generated catalog: %w", err))
	}
}

// lucideModuleDir locates the downloaded Lucide module source directory.
func lucideModuleDir() (string, error) {
	command := exec.Command("go", "mod", "download", "-json", "github.com/kaugesaar/lucide-go")
	output, err := command.Output()
	if err != nil {
		return "", fmt.Errorf("download lucide-go module: %w", err)
	}
	var module struct {
		Dir   string
		Error string
	}
	if err := json.Unmarshal(output, &module); err != nil {
		return "", fmt.Errorf("decode lucide-go module metadata: %w", err)
	}
	if module.Error != "" {
		return "", fmt.Errorf("download lucide-go module: %s", module.Error)
	}
	if strings.TrimSpace(module.Dir) == "" {
		return "", fmt.Errorf("lucide-go module directory is empty")
	}
	return module.Dir, nil
}

// label converts a kebab-case icon name to a display label.
func label(name string) string {
	words := strings.Split(name, "-")
	for index, word := range words {
		if word == "" {
			continue
		}
		words[index] = strings.ToUpper(word[:1]) + word[1:]
	}
	return strings.Join(words, " ")
}

// fail prints an error and terminates generation with a nonzero status.
func fail(err error) {
	_, _ = fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
